### ISSUE TITLE
Issue with Running `app-ios-compose`

### ISSUE THREAD

**Issue by JurajBegovac** [arkivanov/decompose-multiplatform-template#17]
**Issue with Running `app-ios-compose`**

Hi,

I've encountered an issue with running `app-ios-compose` after pulling the master branch.

### Steps to Reproduce

1. **From Android Studio:**
    - I attempted to run `app-ios-compose` but received the following error:
    ```
    'Users/.../decompose-multiplatform-template/app-ios-compose' is not part of the build defined by settings file '/Users/.../decompose-multiplatform-template/settings.gradle.kts'.  If this is an unrelated build, it must have its own settings file.
    ```
    - It appears that the configuration for Android Studio might not be correct.

2. **From Xcode:**
    - I opened the project in Xcode, but encountered an error in `iOSApp.swift`:
    ```
    Cannot find 'ApplicationLifecycle' in scope
    ```
    - I tried cleaning and rebuilding the project, but the same error persists.

### Additional Information

- Running `app-ios-swift` works fine from both Android Studio and Xcode.
- Running `app-desktop` works fine from Android Studio
- Running `app-android` works fine from Android Studio

Any guidance on resolving these issues would be greatly appreciated.

Thank you.

**Comment by JurajBegovac** [comment]
Thank you. It works when I run it from Xcode. However, it still doesn't work when I try to run it from Android Studio. But ok

**Comment by arkivanov** [comment]
Yes, the option to run from Android Studio has been broken since the migration the iOS app to Xcode-based project. There is no any direct Gradle task now. 

I think we should update the template with the changes above, and also remove the iOS run configuration as well for now.
